name: Perform deployment to development environment

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'The region to deploy to'
        required: true
        type: string
        default: 'westus3'

jobs:
  deploy-dev:
    uses: ./.github/workflows/workflow-deploy.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: 'dev'
      region: ${{ github.event.inputs.region }}